name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
        env:
          CI: false
      - name: Post-build cleanup
        run: |
          node << 'EOF'
            const fs = require('fs');
            const path = require('path');
            const packageJson = require('./package.json');
            const indexPath = path.join(`${process.env.PWD}`, 'dist', 'index.html');
            const notFoundPath = path.join(`${process.env.PWD}`, 'dist', '404.html');
            const indexContent = fs.readFileSync(indexPath, 'utf8');
            const updatedContent = indexContent.replaceAll(`"/assets`, `"${packageJson.homepage}/assets`);
            fs.writeFileSync(indexPath, updatedContent);
            fs.writeFileSync(notFoundPath, updatedContent);
          EOF

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
